### ISSUE TITLE
在有道申请智云了翻译实例和应用，但都提示无效的key

### ISSUE THREAD

**Issue by xianghongai** [ShanaMaid/terminal-translate#3]
![1](https://user-images.githubusercontent.com/2075006/31366459-86e08d62-ada3-11e7-889a-2245d96f15ec.png)

![2](https://user-images.githubusercontent.com/2075006/31366460-8721c372-ada3-11e7-8404-631c5ba8f429.png)

给有道智云发了邮件，还没回复。

**Comment by ShanaMaid** [comment]
有道引擎无法使用就暂时切一下baidu或者爱词霸吧
