### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by wezhyn** [ShanaMaid/terminal-translate#5]
~ tl -h
/usr/bin/env: ‘node\r’: No such file or directory
~ tl great
/usr/bin/env: ‘node\r’: No such file or directory
百度了一下，说是sudo ln -s /usr/bin/nodejs /usr/bin/node
但是已经存在了这个链接文件，也是不行

**Comment by ShanaMaid** [comment]
@wezhyn 
/usr/local/lib/node_modules/
这个目录下你看看有没有terminal-translate，估计你的node默认安装路径有问题

试试运许下面这个命令再重新安装试试
sudo apt-get install nodejs-legacy

**Comment by ShanaMaid** [comment]
@wenzhyn，我定位了一下，应该是bin文件的换行字符编码的问题，你重新安装一下就好了
