### ISSUE TITLE
有道单词本功能

### ISSUE THREAD

**Issue by fangjj215** [ShanaMaid/terminal-translate#6]
你好，能否添加一个命令，将单词添加到有道单词本，这样可以用手机有道背单词

**Comment by fangjj215** [comment]
看介绍，好像是使用了有道AI,而不是调用http，使用这个网站 http://dict.youdao.com/ 进行的翻译

**Comment by ShanaMaid** [comment]
开发初衷仅是一个终端翻译工具，如有需求欢迎pr

**Comment by fangjj215** [comment]
> 开发初衷仅是一个终端翻译工具，如有需求欢迎pr

好的。
