### ISSUE TITLE
issue when using proxy

### ISSUE THREAD

**Issue by hugang** [ShanaMaid/terminal-translate#7]
I have a proxy network , 'http://user:passwd@ip:port' , I can't get the result.
公司网络使用'http://user:passwd@ip:port'的网关，翻译时不能返回结果。

**Comment by ShanaMaid** [comment]
跟代理应该无关，是否公司禁了外网？

**Comment by hugang** [comment]
没有禁止外网，chrome浏览器配置proxy可以访问外网。

**Comment by ShanaMaid** [comment]
尝试ss开启全局代理？

**Comment by hugang** [comment]
我尝试了将http换成request，可以返回结果。

const http = require('request');

let url = 'http://fanyi.youdao.com/openapi.do?';

for (let item in data) {
url += `${item}=${data[item]}&`;
}

url = encodeURI(url);

http.post({
  // access api
  url: url,
  // default get
  method: 'GET',
  // proxy
  proxy: 'http://usr:pwd@my-proxy.com:8080'
}, (error, res, body) => {
  if(error) {
    // error handle
  }
  
  // access successful
  console.log(body);
});

**Comment by ShanaMaid** [comment]
跟npm模块没有关系，是因为你配置了
```
proxy: 'http://usr:pwd@my-proxy.com:8080'
```
开启全局代理就行了
